### ISSUE TITLE
PHP Parse Error – yii\base\ErrorException

### ISSUE THREAD

**Issue by des1roer** [mimicreative/yii2-react#1]
PHP Parse Error – yii\base\ErrorException

syntax error, unexpected '==' (T_IS_EQUAL), expecting ']'

![screenshot_55](https://cloud.githubusercontent.com/assets/10970793/18902546/1a55d544-856d-11e6-8371-6595b53ceef2.png)

**Comment by lshaf** [comment]
can you give me your PHP version?
